# Generated by Django 5.2.3 on 2025-06-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysiscache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisCache',
        ),
    ]
